using Content.Shared._ES.Cargo.Storeroom.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Cargo.Storeroom.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStoreroomEntryControl : BoxContainer
{
    public ESStoreroomEntry Entry { get; set; } = new();

    public ESStoreroomEntryControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(ESStoreroomEntry entry)
    {
        Entry = entry;

        Icon.SetPrototype(entry.IconEntity);
        TextLabel.Text = Loc.GetString("es-warehouse-manifest-entry-label", ("name", entry.Name), ("count", entry.Count));
    }
}

