using System.Linq;
using Content.Shared._ES.Cargo.Storeroom.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Cargo.Storeroom.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStoreroomContainerControl : BoxContainer
{
    public ESStoreroomContainerEntry Entry { get; set; } = new();

    public ESStoreroomContainerControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(ESStoreroomContainerEntry container, int count)
    {
        Entry = container;

        Icon.SetPrototype(container.IconEntity);
        TextLabel.Text = Loc.GetString("es-warehouse-manifest-container-label", ("name", container.Name), ("count", count));

        ToggleButton.Disabled = container.Contents.Count == 0;
        ToggleButton.OnPressed += _ =>
        {
            EntryContainer.Visible = !EntryContainer.Visible;
        };

        EntryContainer.Children.Clear();
        foreach (var entry in container.Contents.OrderBy(e => e.Name))
        {
            var control = new ESStoreroomEntryControl();
            control.Update(entry);
            EntryContainer.AddChild(control);
        }
    }
}

