using System.Linq;
using Content.Client.Station;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Cargo.Storeroom.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Cargo.Storeroom.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESWarehouseManifestWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly StationSystem _station;

    public ESWarehouseManifestWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _station = _entityManager.System<StationSystem>();

        FilterEdit.OnTextChanged += args =>
        {
            foreach (var child in EntryContainer.Children)
            {
                if (child is not ESStoreroomContainerControl container)
                    continue;

                foreach (var subChild in container.EntryContainer.Children)
                {
                    if (subChild is not ESStoreroomEntryControl subControl)
                        continue;

                    subControl.Visible = string.IsNullOrEmpty(args.Text) ||
                                         container.Entry.Name.Contains(args.Text, StringComparison.InvariantCultureIgnoreCase) ||
                                         subControl.Entry.Name.Contains(args.Text, StringComparison.InvariantCultureIgnoreCase);
                }

                container.Visible = string.IsNullOrEmpty(args.Text) ||
                                    container.EntryContainer.Children.Any(c => c.Visible) ||
                                    container.Entry.Name.Contains(args.Text, StringComparison.InvariantCultureIgnoreCase);
            }
        };

        ResetButton.OnPressed += _ =>
        {
            FilterEdit.SetText(string.Empty, true);
        };
    }

    public void Update(EntityUid owner)
    {
        if (_station.GetOwningStation(owner) is not { } station ||
            !_entityManager.TryGetComponent<ESStoreroomStationComponent>(station, out var storeroom))
            return;

        EntryContainer.Children.Clear();
        foreach (var (container, count) in storeroom.Stock.OrderBy(c => c.Key.Name))
        {
            var control = new ESStoreroomContainerControl();
            control.Update(container, count);
            EntryContainer.AddChild(control);
        }
    }
}

