using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Cargo.Requests.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._ES.Cargo.Requests.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESRequestCreationWindow : FancyWindow
{
    public event Action<string>? OnRequestConfirm;

    public ESRequestCreationWindow()
    {
        RobustXamlLoader.Load(this);

        CancelButton.StyleClasses.Add("ButtonColorRed");

        BodyLineEdit.OnTextChanged += _ =>
        {
            var text = Rope.Collapse(BodyLineEdit.TextRope);
            ConfirmButton.Disabled = text.Length > ESCargoRequestConsoleComponent.MaxBodyLength;
        };

        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ =>
        {
            OnRequestConfirm?.Invoke(Rope.Collapse(BodyLineEdit.TextRope));
            Close();
        };
    }
}

